apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
spec:
  selector:
    matchLabels:
      app: server1
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1
        image: server1:1.2
        #imagePullPolicy: Never
        #imagePullPolicy: Always
        ports:
        - containerPort: 8080