apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
spec:
  selector:
    matchLabels:
      app: server1
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1
        image: server1:1.2
        volumeMounts:
        - mountPath: /test-volume
          name: test-volume
        #imagePullPolicy: Never
        #imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: test-volume
        hostPath:
          path: /volumes/test-volume
          type: DirectoryOrCreate
---

apiVersion: v1
kind: Service
metadata:
  name: server1
  labels:
    run: server1
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: server1
